variables:
  - &rust_image "rust:1.81"
  - &install_binstall "wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz && tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz && cp cargo-binstall /usr/local/cargo/bin"

steps:
  build_release:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
      - tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
      - rustup target add wasm32-unknown-unknown
      - ./cargo-binstall -y trunk
      - export PATH="$PATH:$(pwd)/.cargo_home/bin/"
      - ls -lah assets
      - ls -lah assets/dist
      - ./scripts/build_release.sh
      - ls -lah assets/dist
    when:
      - event: tag

  publish_release:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - ibis.gz
      title: ${CI_COMMIT_TAG##v}
      api-key:
        from_secret: github_token
    when:
      - event: tag

services:
  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ibis
      POSTGRES_PASSWORD: password
