variables:
  - &rust_image "rust:1.81-slim"
  - &install_binstall "wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz && tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz && cp cargo-binstall /usr/local/cargo/bin"
  - &install_cargo_leptos "cargo-binstall -y cargo-leptos@0.2.24"

steps:
  build_release:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo_home
    commands:
      - apt-get update
      - apt-get install postgresql -y --no-install-recommends --no-install-suggests npm wget
      - npm install
      - *install_binstall
      - rustup target add wasm32-unknown-unknown
      - *install_cargo_leptos
      - export PATH="$PATH:$(pwd)/.cargo_home/bin/"
      - ./scripts/build_release.sh
    when:
      - event: tag

  publish_release:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - ibis.gz
      title: ${CI_COMMIT_TAG##v}
      api-key:
        from_secret: github_token
    when:
      - event: tag

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ibis
      POSTGRES_PASSWORD: password
