[package]
name = "ibis"
version = "0.1.0"
edition = "2021"

[features]
default = ["ssr"]
ssr = [
  "axum",
  "axum-macros",
  "axum-extra",
  "tower-http",
  "diesel",
  "diesel-derive-newtype",
  "diesel_migrations",
  "tokio",
  "leptos_axum",
  "activitypub_federation",
  "jsonwebtoken"
]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]

[dependencies]
activitypub_federation = { version = "0.5.0-beta.6", features = [
  "axum",
  "diesel",
], default-features = false, optional = true }
anyhow = "1.0.75"
async-trait = "0.1.74"
axum = { version = "0.6.20", optional = true }
axum-macros = { version = "0.3.8", optional = true }
axum-extra = { version = "0.7.7", features = ["cookie"], optional = true }
leptos = "0.5.4"
leptos_meta = "0.5.4"
leptos_router = "0.5.4"
leptos_axum = { version = "0.5.4", optional = true }
bcrypt = "0.15.0"
chrono = { version = "0.4.31", features = ["serde"] }
diesel = { version = "2.1.4", features = [
  "postgres",
  "chrono",
  "uuid",
], optional = true }
diesel-derive-newtype = { version = "2.1.0", optional = true }
diesel_migrations = { version = "2.1.0", optional = true }
diffy = "0.3.0"
enum_delegate = "0.2.0"
env_logger = { version = "0.10.1", default-features = false }
futures = "0.3.29"
hex = "0.4.3"
jsonwebtoken = {version = "9.2.0", optional = true }
rand = "0.8.5"
serde_json = "1.0.108"
sha2 = "0.10.8"
tokio = { version = "1.34.0", features = ["full"], optional = true }
uuid = { version = "1.6.1", features = ["serde"] }
tower-http = { version = "0.4.0", features = ["cors", "fs"], optional = true }
serde = { version = "1.0.192", features = ["derive"] }
url = { version = "2.4.1", features = ["serde"] }
reqwest = { version = "0.11.22", features = ["json", "cookies"] }
log = "0.4"
tracing = "0.1.40"
once_cell = "1.18.0"
wasm-bindgen = "0.2.89"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
time = "0.3.31"
tower = "0.4.13"
markdown-it = "0.6.0"

[dev-dependencies]
pretty_assertions = "1.4.0"

[package.metadata.leptos]
output-name = "ibis"
bin-features = ["ssr"]
lib-features = ["csr"]
site-addr = "127.0.0.1:8131"

[lib]
name = "ibis_lib"
crate-type = ["cdylib", "rlib"]

# This profile significantly speeds up build time. If debug info is needed you can comment the line
# out temporarily, but make sure to leave this in the main branch.
[profile.dev]
debug = 0
