[package]
name = "ibis"
version = "0.1.5"
edition = "2021"

[features]
default = ["ssr"]
ssr = [
  "axum",
  "axum-macros",
  "axum-extra",
  "tower-http",
  "diesel",
  "diesel-derive-newtype",
  "diesel_migrations",
  "tokio",
  "leptos_axum",
  "activitypub_federation",
  "jsonwebtoken",
  "katex/duktape",
  "leptos/ssr",
  "leptos-use/ssr",
]
hydrate = [
  "leptos/hydrate",
  "leptos_meta/hydrate",
  "leptos_router/hydrate",
  "katex/wasm-js",
]

# This profile significantly speeds up build time. If debug info is needed you can comment the line
# out temporarily, but make sure to leave this in the main branch.
[profile.dev]
debug = 0

[profile.release]
lto = "thin"
strip = true

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[lints.clippy]
dbg_macro = "deny"
unwrap_used = "deny"

[dependencies]
activitypub_federation = { version = "0.6.0-alpha2", features = [
  "axum",
  "diesel",
], default-features = false, optional = true }
anyhow = "1.0.89"
async-trait = "0.1.83"
axum = { version = "0.7.7", optional = true }
axum-macros = { version = "0.4.2", optional = true }
axum-extra = { version = "0.9.4", features = ["cookie"], optional = true }
leptos = "0.6.15"
leptos_meta = "0.6.15"
leptos_router = "0.6.15"
leptos_axum = { version = "0.6.15", optional = true }
bcrypt = "0.15.1"
chrono = { version = "0.4.38", features = ["serde"] }
diesel = { version = "2.2.4", features = [
  "postgres",
  "chrono",
  "uuid",
  "r2d2",
], optional = true }
diesel-derive-newtype = { version = "2.1.2", optional = true }
diesel_migrations = { version = "2.2.0", optional = true }
diffy = "0.4.0"
enum_delegate = "0.2.0"
env_logger = { version = "0.11.5", default-features = false }
futures = "0.3.30"
hex = "0.4.3"
jsonwebtoken = { version = "9.3.0", optional = true }
rand = "0.8.5"
serde_json = "1.0.128"
sha2 = "0.10.8"
tokio = { version = "1.40.0", features = ["full"], optional = true }
uuid = { version = "1.10.0", features = ["serde"] }
tower-http = { version = "0.6.1", features = ["cors", "fs"], optional = true }
serde = { version = "1.0.210", features = ["derive"] }
url = { version = "2.5.2", features = ["serde"] }
reqwest = { version = "0.12.8", features = ["json", "cookies"] }
log = "0.4"
tracing = "0.1.40"
once_cell = "1.20.1"
wasm-bindgen = "0.2.93"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
time = "0.3.36"
tower = "0.5.1"
markdown-it = "0.6.1"
web-sys = "0.3.70"
config = { version = "0.14.0", features = ["toml"] }
doku = "0.21.1"
smart-default = "0.7.1"
tower-layer = "0.3.3"
katex = { version = "0.4", default-features = false }
include_dir = "0.7.4"
markdown-it-block-spoiler = "1.0.0"
markdown-it-heading-anchors = "0.3.0"
markdown-it-footnote = "0.2.0"
markdown-it-sub = "1.0.0"
markdown-it-sup = "1.0.0"
leptos-use = "0.13.6"

[dev-dependencies]
pretty_assertions = "1.4.1"

[package.metadata.leptos]
output-name = "ibis"
assets-dir = "assets"
bin-features = ["ssr"]
lib-features = ["hydrate"]
lib-profile-release = "wasm-release"

[lib]
crate-type = ["cdylib", "rlib"]
